spring:
  application:
    name: adodenhaag-backend
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: abhi
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

# ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include: '*'
# HEALTH ENDPOINT
management.endpoint.health.show-details: always
# INFO ENDPOINT CONFIGURATION
